// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: transfer.sql

package repository

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfer (amount, from_account_id, to_account_id)
VALUES ($1, $2, $3)
RETURNING id, amount, from_account_id, to_account_id
`

type CreateTransferParams struct {
	Amount        string
	FromAccountID int32
	ToAccountID   int32
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer, arg.Amount, arg.FromAccountID, arg.ToAccountID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.FromAccountID,
		&i.ToAccountID,
	)
	return i, err
}
